apiVersion: v2
name: inde
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
keywords:
  - INDE
  - geoserver
  - geonetwork
dependencies:
  - name: geoserver
    version: "0.1.0"
    repository: "https://nds-cprm.github.io/helm-charts/"
    condition: geoserver.enabled
  - name: geonetwork
    version: "0.1.0"
    repository: "https://nds-cprm.github.io/helm-charts/"
    condition: geonetwork.enabled
maintainers:
  - name: Carlos Eduardo Mota
    email: carlos.mota@sgb.gov.br
icon: "https://inde.gov.br/img/INDE%20Logo.png"