apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.overrides.html.name }}
  labels:
    {{- include "inde.labels" . | nindent 4 }}
data:
  index.html: |-
{{ ( tpl ( .Files.Get "files/index.html" ) . ) | indent 4 }}